### ISSUE TITLE
command `expand line selections` don't act like vscode

### ISSUE THREAD

**Issue by tommyme** [KrazyManJ/obsidian-keyshots#11]
In vscode, `expand line selections` can be called multiple times and it'll select the next line in the next time
![test](https://github.com/user-attachments/assets/2af0a32f-8945-415a-9e6f-e43eda695072)

If you selected Beginning of Line to End of Line, pressing ctrl L again will select from the beginning of the current line to the beginning of the next line

Sometimes, I want to select multiple lines and don't wanna use my mouse, I'll hit `ctrl L` a few times on vscode, It's a useful feature for me.

I feel like it's a bit more complicated to achieve this than I thought, because of the selection merging issues in a multi-cursor scenario.
![test2](https://github.com/user-attachments/assets/84d9033e-d1cf-456a-96a6-d2c958eac86b)

BTW, the plugin is very good, well documented, and the code is well abstracted and structured.

Thanks for reading this :).

**Comment by KrazyManJ** [comment]
Hello @tommyme, thank you for your issue post.

Currently I've fixed behavior of `Expand line selections` command to act like visual studio code one (that means that when it is already expanded, it will add next line to selection, if not expanded, it will expand). I will inform you through this issue post when this fix will be public for you to try. Please watch out for this issue post for confirming desired behavior of this command to mark it as solved in the future.

Thank you for your commitment and posting this issue post to make Keyshots a better plugin! ❤️

**Comment by tommyme** [comment]
Thanks alot, I'll confirm the behavior of this command when new version is published.❤️

**Comment by KrazyManJ** [comment]
Hey, sorry for the response after 2 months but update for this is finally out in latest release.

See https://github.com/KrazyManJ/obsidian-keyshots/releases/tag/2.4.0 and tell me.

**Comment by tommyme** [comment]
Thanks alot, It works!
