### ISSUE TITLE
[Bug] Failed to install plugin

### ISSUE THREAD

**Issue by damiankorcz** [KrazyManJ/obsidian-keyshots#2]
Hey @KrazyManJ,
The plugin fails to install from the Community Plugins store. You appear to have set your version in `manifest.json` and `versions.json` to 1.5.0 and the latest public release is 1.4.0 resulting in a 404 error.
![image](https://user-images.githubusercontent.com/7290097/211207882-9f9d6edc-7c5a-4bbe-9632-03fae655a161.png)
![image](https://user-images.githubusercontent.com/7290097/211207865-837ea2eb-915c-4e5c-8aef-175390c1fa23.png)

**Comment by KrazyManJ** [comment]
@damiankorcz Thank you for your issue post, now I've commited repaired files, so it is possible to download and install it again!

**Comment by damiankorcz** [comment]
It does indeed work now. Thanks!
