### ISSUE TITLE
delete the whole codeblock section

### ISSUE THREAD

**Issue by trevim99** [KrazyManJ/obsidian-keyshots#9]
Thank you for your keyshots .
How could I do to delete or select whole codeblock with hot key?
Thank you.

**Comment by KrazyManJ** [comment]
Hello @trevim99, thank you for your issue post.

This is now not possible in Keyshots (at least with one command). But on computer it can be achieved by these steps:

1. Having cursor at the top or bottom of code block
2. Then move cursor in direction of codeblock with arrow keys <kbd>↑</kbd>, <kbd>↓</kbd> while holding <kbd>Shift</kbd> key.
3. After reaching next bound of code block, to make sure, that everything is selected, use `Keyshots: Expand line selection` command (in default with <kbd>Alt</kbd> + <kbd>E</kbd> but it depends on what preset you have chosen)
4. Then press <kbd>Backspace ←</kbd> key or <kbd>Delete</kbd> key, to finally remove it

Command for removing code block is something, that you can make done in few steps, and I hope so, you don't type 100 code blocks on daily basis to actually have command for removing them.

I am sorry but I am closing this issue as not planned. Have a great day and thank you for helping Keyshots to become a better plugin. Feel free to leave other ideas in new issue post.
